[0m[[0m[31merror[0m] [0m[0m/Users/shaileshpilare/ml-workshop/Case-Study-Malware-Analysis/Section3-Chapter2/MalwareFeatureEngineeringApp/src/main/scala/FeatureEngineering2.scala:48:5: not found: value test_df[0m
[0m[[0m[31merror[0m] [0m[0m    test_df.groupBy("label").count().show()[0m
[0m[[0m[31merror[0m] [0m[0m    ^[0m
[0m[[0m[31merror[0m] [0m[0mone error found[0m
